#define MENU_LEFT -1
#define MENU_RIGHT -2
#define MENU_CONFIRM_EXIT -3
#define MENU_CONFIRM 1
#define MENU_EXIT 0
#define MODE_VOLTAGE 0
#define MODE_CURRENT 1
#define MODE_RESISTANCE 2
#define MODE_LIGHT 3
#define MODE_CONTINUITY 4
#define MODE_TRANSISTOR 5
#define MODE_DIODE 6
#define MODE_CAPACITOR 7
#define MODE_INDUCTOR 8
#define MODE_RMS 9
#define MODE_FREQUENCY 10
#define MODE_SIGGEN 11
#define MODE_DISPLAY 0
#define MODE_SET 1

#define STRING_AMPS "Amps"
#define STRING_VOLTAGE "Volts"
#define STRING_RESISTANCE "Res"
#define STRING_LIGHT "Light"
#define STRING_CONTINUITY "Cont"
#define STRING_TRANSISTOR "Trans"
#define STRING_DIODE "Dio"
#define STRING_CAPACITOR "Cap"
#define STRING_INDUCTOR "Ind"
#define STRING_RMS "Rms"
#define STRING_FREQUENCY "Freq"
#define STRING_TOGGLE "Tog"

#define ADC_VOLTAGE
#define ADC_CURRENT
#define CONTINUITY_RAW_CAP 22700

#define RESISTANCE_MULTIPLIER 100000/.64
